# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce402f9edf33a6f73a1c2d25ad2eefc9f74cc07994891d7268b3168627bbde5b48462f2c72c13689b8a84725f5e60eff27487856b1ee1a5d2724855a617688f0

test:
  secret_key_base: 04a07a38a9a0bb65e365e920e58d5eb18d1c58dd9d7d9cdd47afbae431fa036069b5aee04db3ae422f09059890a151a5c99030919bdb1262cac2d9d19f9981b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
